name: Build TMML Encyclopedia

on:
  push:
    branches: [ main, develop ]
    paths: [ 'src/latex/**', 'docs/pdfs/**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: |
          scheme-full
          
    - name: Install additional packages
      run: |
        sudo apt-get update
        sudo apt-get install -y qpdf poppler-utils
        
    - name: Build Encyclopedia
      run: |
        cd src/latex
        # Build twice for stable TOC and cross-references
        latexmk -xelatex TMML_Encyclopedia_OPTIMIZED.tex
        latexmk -xelatex TMML_Encyclopedia_OPTIMIZED.tex
        
    - name: Validate PDF
      run: |
        cd src/latex
        # Check if PDF was generated and get page count
        if [ -f "TMML_Encyclopedia_OPTIMIZED.pdf" ]; then
          echo "✅ PDF generated successfully"
          PAGES=$(pdfinfo TMML_Encyclopedia_OPTIMIZED.pdf | grep Pages | awk '{print $2}' || echo "Unknown")
          echo "📄 Total pages: $PAGES"
          
          if [ "$PAGES" != "Unknown" ] && [ "$PAGES" -gt 10 ]; then
            echo "✅ PDF build successful ($PAGES pages)"
          else
            echo "⚠️  PDF built but page count low ($PAGES pages)"
          fi
        else
          echo "❌ PDF generation failed"
          exit 1
        fi
        
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tmml-encyclopedia-${{ github.sha }}
        path: src/latex/*.pdf
        retention-days: 30