name: Build TMML Encyclopedia Clean

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'src/latex/**', 'docs/pdfs/**' ]

permissions:
  contents: read
  actions: read

jobs:
  build-pdf:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install TeX Live
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended latexmk fonts-noto fonts-dejavu-extra poppler-utils

    - name: Build LaTeX
      working-directory: src/latex
      run: |
        latexmk -xelatex -interaction=nonstopmode -halt-on-error TMML_Encyclopedia_OPTIMIZED.tex
        latexmk -xelatex -interaction=nonstopmode -halt-on-error TMML_Encyclopedia_OPTIMIZED.tex

    - name: Validate
      working-directory: src/latex
      run: |
        test -f TMML_Encyclopedia_OPTIMIZED.pdf && echo "✅ PDF exists" || (echo "❌ No PDF" && exit 1)
        pdfinfo TMML_Encyclopedia_OPTIMIZED.pdf | head -5 || true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: encyclopedia-${{ github.run_id }}
        path: src/latex/TMML_Encyclopedia_OPTIMIZED.pdf
        retention-days: 30
